### ISSUE TITLE
Findings for Sslyze

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/reptor#124]
In the course of restructuring uploaded notes, I will also improve the pushing of Sslyze findings.

* All pushed findings should be aggregated for multiple targets (e. g. only one finding for multiple systems with untrusted certificate)
* The following findings should be created:
   * Issues affecting the certificate (untrusted, SHA1, etc.)
   * Issues affecting web server configuration (misconfigurations, insecure protocols and ciphers)
   * SSL vulnerabilities

**Comment by aronmolnar** [comment]
Ah that's very nice - thanks.

Unfortunately I have done this part already. I used data from https://ciphersuite.info/

**Comment by noraj** [comment]
I does that too to retrieve which cipher suite is weak https://github.com/noraj/tls-map/blob/master/lib/tls_map/app/extended/ciphersuiteinfo.rb
