### ISSUE TITLE
Nessus import only imports 1 host per finding

### ISSUE THREAD

**Issue by Gray-0men** [Syslifters/reptor#156]
![image](https://github.com/Syslifters/reptor/assets/39830524/156b60b9-1813-4a95-8301-5e20144586fb)

in the picture Affected Components should contain dozens of IP's (at least 35+ in my case)
Does the --push-findings function only insert 1 host where I have to put in the rest manually? or is this a bug and it was supposed to populate all hosts the Nessus file has

**Comment by aronmolnar** [comment]
Hi Damian,

It should import all affected components.

`cat nessus.xml | reptor --template-vars` gives you the JSON structure that should be pushed to SysReptor.  
Can you check if the affected_components field is correct there? Like in this sample:

![image](https://github.com/Syslifters/reptor/assets/25219407/8a4335fc-9fef-408c-b828-b3951aa0af2a)

**Comment by aronmolnar** [comment]
Sorry - got it.

It's a bug. We'll try to fix it ASAP.

**Comment by aronmolnar** [comment]
You can upgrade using `pip3 install --upgrade reptor` and now the affected_components should work as expected.

Can you confirm?

**Comment by Gray-0men** [comment]
Fixed, thank you so much

Also, by far the fastest bug response I've ever had on github. Extremely happy
