### ISSUE TITLE
OpenVAS Plugin - ref(s) not available as template variable

### ISSUE THREAD

**Issue by cmahrl** [Syslifters/reptor#165]
When parsing OpenVAS XML files, it appears that references (<refs> and <ref> tags) are not be available as Django template variables after parsing.

Reproduce:
1. Modify OpenVAS finding template global.toml by using refs as template variable. 
2. cat openvas-scan.xml | reptor openvas --push-findings

**Comment by aronmolnar** [comment]
Was fixed in 0.16
