### ISSUE TITLE
Exportfindings does not support ordering of findings

### ISSUE THREAD

**Issue by StephanPillhofer** [Syslifters/reptor#168]
When exporting findings using the `exportfinding` command, the resulting csv isn't ordered based on the ordering configured in the current design of the project. It would be nice if the `exportfinding` command would respect the configured ordering or maybe provide another way of sorting the findings using the commandline.

**Comment by aronmolnar** [comment]
The current implementation respected only custom finding orders, but not the default sorting defined in designs.  
This is now fixed and `exportfindings` should always keep the order that you see in the web UI.

Fix is released in 0.17
