### ISSUE TITLE
Burp import handling with severity / cvss

### ISSUE THREAD

**Issue by byteboltsec** [Syslifters/reptor#175]
Hi @aronmolnar ,
thanks for pushing out the new Burp importer!

As Burp is handling the risk ratings with `severity` and not with `cvss` scoring, a hint in the documentation and adaptions in the Demo projects would be really awesome. Currently, the starter designs are interpreting all Burp findings as `Info` in the rendered PDF, which could cause confusion.

Thank you!

**Comment by byteboltsec** [comment]
Hi @aronmolnar,
thanks for updating the documentation in detail!

I've customized the finding table template which can handle `cvss` and `severity` parallel (like from Burp), feel free do adopt / link / change it.
Hope it will help other SysReptor users 😉 

```js
<tbody>
  <section v-for="finding in findings">
    <tr v-if="(!finding.cvss.vector || finding.cvss.vector === 'n/a') && finding.cvss.score" class="table-row-link"
      :class="'risk-bg-' + finding.severity.value">
      <td class="td-center">
        {{ findings.indexOf(finding) + 1 }}
      </td>
      <td class="td-center">
        <ref :to="finding.id">{{ finding.severity.label }}</ref>
      </td>
      <td>
        <ref :to="finding.id">{{ finding.title }}</ref>
      </td>
      <td class="td-center">
        <ref :to="finding.id" class="ref-page" />
      </td>
    </tr>
    <tr v-else class="table-row-link" :class="'risk-bg-' + finding.cvss.level">
      <td class="td-center">
        {{ findings.indexOf(finding) + 1}}
      </td>
      <td class="td-center">
        <ref :to="finding.id">{{ finding.cvss.score }}</ref>
      </td>
      <td>
        <ref :to="finding.id">{{ finding.title }}</ref>
      </td>
      <td class="td-center">
        <ref :to="finding.id" class="ref-page" />
      </td>
    </tr>
  </section>
</tbody>
```

![table](https://github.com/Syslifters/reptor/assets/122016929/c1706a49-d440-4e41-a448-54e63dd05212)

**Comment by aronmolnar** [comment]
Great, many thanks!
