### ISSUE TITLE
Burp Plugin

### ISSUE THREAD

**Issue by richardschwabe** [Syslifters/reptor#24]
Need a burp scanner plugin.

Requires access to a sample file

**Comment by cybacoffee** [comment]
Hi syslifters, thanks for making the awesome raptor!
Any updates on the reptor importer for Burp and Burp Enterprise XML?
Thanks!

**Comment by aronmolnar** [comment]
Hi cybacoffee,
I hope to implement it this week.

**Comment by cybacoffee** [comment]
Hi @aronmolnar, thank you, sounds great!
If you need Burp Enterprise XML input files, I could provide one!

**Comment by aronmolnar** [comment]
Yes, this would be nice.
I have Burp Pro reports in XML format and it would be nice to know if they're the same.

You can upload here or send us to hello@syslifters.com.

Thanks!

**Comment by aronmolnar** [comment]
Implemented in https://github.com/Syslifters/reptor/commit/72ddc040d72727ba6cff2223edb03b7ce7ebec9a

Released in https://github.com/Syslifters/reptor/releases/tag/0.20

Upgrade with `pip3 install --upgrade reptor`

Docs at: https://docs.sysreptor.com/cli/tools/burp/
